import { Info } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

/**
 * Shown only when the AI analysis fell back to the deterministic report
 * despite a key being expected. The dashboard gates rendering on
 * meta.source === "fallback" && meta.keyExpected.
 */
export function FallbackBanner() {
  return (
    <Alert variant="info">
      <Info aria-hidden="true" />
      <AlertTitle>AI brain unavailable</AlertTitle>
      <AlertDescription>
        Showing a deterministic report. All scores and readiness numbers are
        exact — only the written coaching is generated by formula instead of AI.
      </AlertDescription>
    </Alert>
  );
}
